include_guard()

string(MAKE_C_IDENTIFIER ${PROJECT_NAME} PROJECT_NAME_SANITIZED)
string(TOUPPER ${PROJECT_NAME_SANITIZED} PROJECT_NAME_UPPER)
string(TOLOWER ${PROJECT_NAME_SANITIZED} PROJECT_NAME_LOWER)
